horam/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('horam.web.urls')),
    path('', include('user_sessions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_sessions/urls.py
from django.conf.urls import url
from user_sessions.views import SessionDeleteOtherView

from .views import SessionDeleteView, SessionListView

app_name = 'user_sessions'
urlpatterns = [
    url(
        regex=r'^account/sessions/$',
        view=SessionListView.as_view(),
        name='session_list',
    ),
    url(
        regex=r'^account/sessions/other/delete/$',
        view=SessionDeleteOtherView.as_view(),
        name='session_delete_other',
    ),
    url(
        regex=r'^account/sessions/(?P<pk>\w+)/delete/$',
        view=SessionDeleteView.as_view(),
        name='session_delete',
    ),
]

horam/web/templates/members/deactivate.html
{% extends 'centerpage.html' %}

{% block title %}Deaktivovať používateľa{% endblock %}

{% block content %}

<h1>Deaktivovať používateľa {{ member.username }}</h1>

<p>Naozaj deaktivovať používateľa {{ member.username }}?</p>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<ul>
    {{ form.as_ul }}
</ul>

<button type="submit" class="material-button">Deaktivovať</button>
</form>

{% endblock %}

horam/web/templates/members/detail.html
{% extends 'centerpage.html' %}

{% block title %}Profil{% endblock %}

{% block content %}

<h1>{{ member.person.nickname }}</h1>

{% if member.person.avatar %}
    <p>
        <img src="{{ member.person.avatar.url }}" alt="Avatar pre {{ member.person.nickname }}"/>
    </p>
{% endif %}

<p>Prezývka: {{ member.person.nickname }}<br />
    Pohlavie: {% if member.person.is_male %}muž{% else %}žena{% endif %}<br />
    E-mail: <a href="mailto:{{ member.email }}">{{ member.email }}</a><br />
    Konto vytvorené: {{ member.date_joined }}<br />
    Naposledy aktívny: {{ member.last_login }}<br />
</p>

{% if can_edit %}
    <ul>
    <li><a href="{% url 'members_edit' member.username %}">Upraviť profil</a></li>
{% if is_self %}
    <li><a href="{% url 'password_change' %}">Zmeniť heslo</a></li>
    <li><a href="{% url 'user_sessions:session_list' %}">Aktívne relácie</a></li>
{% endif %}
{% if can_deactivate %}
    <li><a href="{% url 'members_deactivate' member.username %}">Deaktivovať</a></li>
{% endif %}
    </ul>
{% endif %}

{% endblock %}

horam/web/templates/members/edit.html
{% extends 'centerpage.html' %}

{% block title %}Profil{% endblock %}

{% block content %}

<h1>Profil</h1>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<ul>
    {{ form.as_ul }}
</ul>

<button type="submit" class="material-button">Uložiť zmeny</button>
</form>

{% endblock %}

horam/web/templates/members/list.html
{% extends 'centerpage.html' %}
{% block title %}Členovia{% endblock %}
{% block content %}
    <h1>Členovia</h1>
    <table>
    {% for member in members %}
        <tr>
            <td>{% include 'avatar.html' with person=member.person %}</td>
            <td><a href="{% url 'members_detail' member.username %}">{{ member.person.nickname }}</a>
                {% if member.is_staff %}<span class="admin-badge">admin</span>{% endif %}
            </td>
            {% if user.is_staff %}
            <td>
                <a href="{% url 'members_edit' member.username %}">upraviť</a>
                <a href="{% url 'admin:web_user_change' member.id %}">admin</a>
            </td>
            {% endif %}
            <td><a href="mailto:{{ member.email }}">{{ member.email }}</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}